# Generated by Django 2.2.2 on 2019-09-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_studentname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentName',
        ),
    ]
