# Generated by Django 2.2.2 on 2019-07-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='先生还是女士')),
                ('first_name', models.CharField(max_length=32, verbose_name='姓')),
                ('last_name', models.CharField(max_length=32, verbose_name='名')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号码')),
                ('address', models.CharField(max_length=32, verbose_name='居住地址')),
                ('district', models.CharField(max_length=32, verbose_name='区')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('zipcode', models.CharField(max_length=32, verbose_name='邮政编码')),
            ],
        ),
    ]
