# Generated by Django 2.2.2 on 2019-07-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group1', models.CharField(max_length=32, verbose_name='选择项')),
                ('description', models.CharField(max_length=128, verbose_name='输入段')),
                ('choice1', models.CharField(max_length=32, null=True, verbose_name='选择一')),
                ('choice2', models.CharField(max_length=32, null=True, verbose_name='选择二')),
                ('choice3', models.CharField(max_length=32, null=True, verbose_name='选择三')),
                ('occupation', models.CharField(max_length=32, verbose_name='职业')),
                ('income', models.CharField(max_length=32, verbose_name='收入水平')),
                ('age', models.CharField(max_length=32, verbose_name='年龄')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('message', models.CharField(max_length=128, verbose_name='消息')),
            ],
        ),
    ]
