# Generated by Django 2.2.6 on 2019-10-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=20)),
                ('port', models.CharField(max_length=20)),
                ('Anonymity', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=50)),
                ('response_time', models.CharField(max_length=20)),
                ('Last_validation_time', models.CharField(max_length=20)),
            ],
        ),
    ]
