# Generated by Django 2.2.2 on 2019-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
    ]
