# Generated by Django 2.2.2 on 2019-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicaltions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='全名')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('address1', models.CharField(max_length=32, null=True, verbose_name='地址1')),
                ('address2', models.CharField(max_length=32, null=True, verbose_name='地址2')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('zipcode', models.CharField(max_length=32, verbose_name='邮编')),
                ('gender', models.CharField(max_length=32, verbose_name='性别')),
                ('expectedsalary', models.CharField(max_length=32, verbose_name='预计薪酬')),
                ('browse', models.CharField(max_length=32, null=True, verbose_name='上传文件')),
                ('message', models.CharField(max_length=128, verbose_name='建议')),
            ],
        ),
    ]
